// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUJ1oGLGdguRuUIKOr-3zxkzJAVYEmCGM',
    appId: '1:1025950549050:web:24aefd9b288a3e8186a103',
    messagingSenderId: '1025950549050',
    projectId: 'gunnell-cemetery',
    authDomain: 'gunnell-cemetery.firebaseapp.com',
    storageBucket: 'gunnell-cemetery.appspot.com',
    measurementId: 'G-P3JE8ZENSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAld8kLtlQ6pk6BUZjaEkWLTjXI-1BZgfQ',
    appId: '1:1025950549050:android:7acd6661fd1ad71786a103',
    messagingSenderId: '1025950549050',
    projectId: 'gunnell-cemetery',
    storageBucket: 'gunnell-cemetery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0Ipq_QPGZUAQ2V1eztR7vcYw2AD-3Lk',
    appId: '1:1025950549050:ios:aed84c2046c2c8aa86a103',
    messagingSenderId: '1025950549050',
    projectId: 'gunnell-cemetery',
    storageBucket: 'gunnell-cemetery.appspot.com',
    iosBundleId: 'com.example.gunnellCemeteryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0Ipq_QPGZUAQ2V1eztR7vcYw2AD-3Lk',
    appId: '1:1025950549050:ios:aed84c2046c2c8aa86a103',
    messagingSenderId: '1025950549050',
    projectId: 'gunnell-cemetery',
    storageBucket: 'gunnell-cemetery.appspot.com',
    iosBundleId: 'com.example.gunnellCemeteryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUJ1oGLGdguRuUIKOr-3zxkzJAVYEmCGM',
    appId: '1:1025950549050:web:24aefd9b288a3e8186a103',
    messagingSenderId: '1025950549050',
    projectId: 'gunnell-cemetery',
    authDomain: 'gunnell-cemetery.firebaseapp.com',
    storageBucket: 'gunnell-cemetery.appspot.com',
    measurementId: 'G-P3JE8ZENSS',
  );

}